projects/common-consumption/src/lib/accordion/accordion-item/accordion-item.component.spec.ts
projects/common-consumption/src/lib/accordion/accordion-item/accordion-item.component.ts
publish.sh

Code coverage for an accordion item component is 100%
overall 10% coverage increased

test: added tests for accordion component

---

projects/common-consumption/src/lib/card/course-card/course-card.component.html
projects/common-consumption/src/lib/card/library-card/library-card.component.html
projects/common-consumption/src/lib/card/library-card/library-card.component.scss
projects/common-consumption/src/lib/card/member-card/member-card.component.html
projects/common-consumption/src/lib/card/member-card/member-card.component.scss
projects/common-consumption/src/lib/card/member-card/member-card.component.ts

Issue#SH-515 Group Creation CC UI fixes - processing loader completion UI and kabab menu UI fix

---

projects/common-consumption/package.json

Issue #SB-20771 fix: updated package version

Issue #SB-20771 fix: updated package version

---

projects/common-consumption/package.json
projects/common-consumption/src/lib/assets/images/sprite.svg

Issue #SB-20771 fix: updated minimize icon to exit fullscreen

Issue #SB-20771 fix: updated minimize icon to exit fullscreen

---

projects/common-consumption/package.json
projects/common-consumption/src/lib/card/toc-card/toc-card.component.html
projects/common-consumption/src/lib/card/toc-card/toc-card.component.scss
projects/common-consumption/src/lib/card/toc-card/toc-card.component.ts
projects/common-consumption/src/lib/content-details/toc-curriculum/toc-curriculum.component.html
projects/common-consumption/src/lib/content-details/toc-curriculum/toc-curriculum.component.ts

- Issue #SB-21233 fix: Added score label for sb-toc-card

Issue #SB-21233 fix: Added score label for sb-toc-card

---

projects/common-consumption/src/lib/card/toc-card/toc-card.component.html
projects/common-consumption/src/lib/card/toc-card/toc-card.component.ts
projects/common-consumption/src/lib/content-details/toc-child-item/toc-child-item.component.html
projects/common-consumption/src/lib/content-details/toc-child-item/toc-child-item.component.ts
projects/common-consumption/src/lib/content-details/toc-curriculum/toc-curriculum.component.html
projects/common-consumption/src/lib/content-details/toc-curriculum/toc-curriculum.component.ts

- Issue #SB-21233 feat: Best score label added for course.

Issue #SB-21233 feat: Best score label added for course.

---

projects/common-consumption/src/lib/card/toc-card/toc-card.component.ts

- Issue #SB-21233 fix: Max attempts condition updated

Issue #SB-21233 fix: Max attempts condition updated

---

projects/common-consumption/package.json
projects/common-consumption/src/lib/card/toc-card/toc-card.component.ts

- Issue #SB-21233 fix: Updated condition for best score

Issue #SB-21233 fix: Updated condition for best score

---

projects/common-consumption/src/lib/card/course-curiculum-card/course-curiculum-card.component.ts

https://project-sunbird.atlassian.net/browse/SB-22918

my group page detail accessibility fix

---

projects/common-consumption/src/lib/accordion/accordion-body/accordion-body.component.scss
projects/common-consumption/src/lib/accordion/accordion-header/accordion-header.component.scss
projects/common-consumption/src/lib/accordion/accordion-item/accordion-item.component.scss
projects/common-consumption/src/lib/card/course-card/course-card.component.scss
projects/common-consumption/src/lib/card/course-curiculum-card/course-curiculum-card.component.scss
projects/common-consumption/src/lib/card/group-card/group-card.component.scss
projects/common-consumption/src/lib/card/library-card-v2/library-card-v2.component.scss
projects/common-consumption/src/lib/card/library-card-v3/library-card-v3.component.html
projects/common-consumption/src/lib/card/library-card-v3/library-card-v3.component.scss
projects/common-consumption/src/lib/card/library-card/library-card.component.scss
projects/common-consumption/src/lib/layout/library-cards-grid/library-cards-grid.component.scss
projects/common-consumption/src/lib/library-filters/library-filters/library-filters.component.scss
projects/common-consumption/src/lib/pills-grid/pill-item/pill-item.component.scss

Issue #SB-22830 darktheme changes - changed colors to element based variables

---

projects/common-consumption/package.json
projects/common-consumption/src/lib/accordion/accordion-header/accordion-header.component.html
projects/common-consumption/src/lib/card/member-card/member-card.component.ts

Mobile accessibility color contrast fix

mobile accessibility color contrast fix

---

projects/common-consumption/src/lib/accordion/accordion-body/accordion-body.component.scss
projects/common-consumption/src/lib/accordion/accordion-header/accordion-header.component.scss
projects/common-consumption/src/lib/accordion/accordion-item/accordion-item.component.scss
projects/common-consumption/src/lib/card/course-curiculum-card/course-curiculum-card.component.scss
projects/common-consumption/src/lib/card/group-card/group-card.component.scss
projects/common-consumption/src/lib/card/library-card-v2/library-card-v2.component.scss
projects/common-consumption/src/lib/card/library-card-v3/library-card-v3.component.scss
projects/common-consumption/src/lib/card/library-card/library-card.component.scss
projects/common-consumption/src/lib/card/member-card/member-card.component.scss
projects/common-consumption/src/lib/card/notification-card/notification-card.component.scss
projects/common-consumption/src/lib/card/toc-card/toc-card.component.scss
projects/common-consumption/src/lib/content-details/toc-curriculum/toc-curriculum.component.scss
projects/common-consumption/src/lib/content-details/toc-item/toc-item.component.scss
projects/common-consumption/src/lib/faq/faq/faq.component.scss
projects/common-consumption/src/lib/layout/library-cards-grid/library-cards-grid.component.scss
projects/common-consumption/src/lib/layout/library-cards-hlist/library-cards-hlist.component.scss
projects/common-consumption/src/lib/layout/library-cards-stack/library-cards-stack.component.scss
projects/common-consumption/src/lib/library-filters/library-filters/library-filters.component.scss
projects/common-consumption/src/lib/pills-grid/pill-item/pill-item.component.scss
projects/common-consumption/src/lib/pills-grid/pills-grid/pills-grid.component.scss

Issue #SB-22830 darktheme changes - css varaible :root issue fix for mobile and portal

---

projects/common-consumption/package.json
projects/common-consumption/src/lib/card/library-card/library-card.component.html

Issue #SB-24014 fix: selected item not highlighting while adding activities

---

projects/common-consumption/src/lib/card/member-card/member-card.component.ts

profile page contrast issue fix

SB-23782-profile page contrast issue fix

---

.circleci/config.yml
package-lock.json

Issue #SB-21675 fix: circleCI build

Issue #SB-21675 fix: circleCI build

---

projects/common-consumption/src/lib/card/library-card-v2/library-card-v2.component.html

https://project-sunbird.atlassian.net/browse/SB-24329

Issue SB-24329: keyboard accessibility fix

---

projects/common-consumption/package.json
projects/common-consumption/src/lib/pills-grid/pill-item/pill-item.component.scss
projects/common-consumption/src/lib/pills-grid/pills-grid/pills-grid.component.html
projects/common-consumption/src/lib/pills-grid/pills-grid/pills-grid.component.scss
projects/common-consumption/src/lib/pills-grid/pills-grid/pills-grid.component.ts

- Issue #SB-23152 fix: Added UI changes for sections page

Issue #SB-23152 fix: Added UI changes for sections page

---

projects/common-consumption/package.json
projects/common-consumption/src/lib/pills-grid/pills-grid/pills-grid.component.html

- Issue #SB-23152 fix: Section button UI changes

Issue #SB-23152 fix: Section button UI changes

---

projects/common-consumption/src/lib/layout/course-cards-hlist/course-cards-hlist.component.html
projects/common-consumption/src/lib/pills-grid/pill-item/pill-item.component.html
projects/common-consumption/src/lib/pills-grid/pills-grid/pills-grid.component.html

https://project-sunbird.atlassian.net/browse/SB-24842

SB-24842 fix: fix for tab explore and home

---

projects/common-consumption/package.json

SB-24842 fix: fix for tab explore and home tab

SB-24842 fix:Update package json

---

projects/common-consumption/package.json
projects/common-consumption/src/lib/accordion/accordion-header/accordion-header.component.html
projects/common-consumption/src/lib/card/banner-card/banner-card.component.html
projects/common-consumption/src/lib/card/course-curiculum-card/course-curiculum-card.component.html
projects/common-consumption/src/lib/card/group-card/group-card.component.html
projects/common-consumption/src/lib/card/toc-card/toc-card.component.html
projects/common-consumption/src/lib/layout/course-cards-hlist/course-cards-hlist.component.html
projects/common-consumption/src/lib/library-filters/library-filters/library-filters.component.html

sb-24890 fix:keyboard accessibility changes

---

projects/common-consumption/package.json

sb-24890 fix: package version updated

---

projects/common-consumption/package.json
projects/common-consumption/src/lib/card/group-card/group-card.component.html
projects/common-consumption/src/lib/card/group-card/group-card.component.scss

Issue #SB-25809 Groups>>Portal>>Groups needs to be accessibility complaint.
